name: 'Build and check'

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          os: [x86_64-mac]

    steps:
      - uses: actions/checkout@v2

      - name: Brew Install
        run: brew install automake libtool boost pkg-config libevent berkeley-db@4 sqlite python

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --with-gui=yes

      - name: make
        run: make

      - name: check
        run: make check
        
