name: 'Build & Check: macOS No QT & No Tests'

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          os: [x86_64-mac]

    steps:
      - uses: actions/checkout@v2

      - name: Brew Install Dependencies
        run: brew install automake boost berkeley-db@4 qt@5 miniupnpc libnatpmp zeromq librsvg openssl pandoc
      
      - name: Brew Install Dependencies
        run: brew link openssl --force

      - name: Install pypandoc
        run: pip3 install pypandoc

      - name: Install scrypt for Python3
        run: pip3 install digibyte_scrypt  
        
      - name: Brew Force Link Openssl
        run: export LDFLAGS="-L/usr/local/opt/openssl/lib -L/usr/local/lib -L/usr/local/opt/expat/lib" && export CFLAGS="-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include" && export CPPFLAGS="-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include"

      - name: Auto Generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure --with-gui=no --disable-tests

      - name: Make
        run: make -j3

      - name: Make Check
        run: make check
        
