name: 'Build & Check: Ubuntu Full QT & Tests'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          os: [x86_64-linux-gnu]

    steps:
      - uses: actions/checkout@v2
      
      - name: Get Dependencies
        run:  sudo apt update && sudo apt-get install build-essential libtool libssl-dev autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev libsqlite3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libqrencode-dev software-properties-common pandoc

      - name: Install pypandoc
        run: pip3 install pypandoc
      
      - name: Install scrypt for Python3
        run: pip3 install digibyte_scrypt

      - name: Install BerkleyDB
        run: |
          sudo add-apt-repository ppa:bitcoin/bitcoin \
          sudo apt update \
          sudo apt install -y libdb4.8-dev libdb4.8++-dev


      - name: Auto Generate
        run: ./autogen.sh

      - name: Configure
        run: ./configure

      - name: Make
        run: make -j3

      - name: Make Check
        run: make check

      - name: Upload Test Suite Log
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-suite-log
          path: /src/test-suite.log
