name: 'Build & check: macOS'

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          os: [x86_64-mac]

    steps:
      - uses: actions/checkout@v2

      - name: Brew Install
        run: brew install automake boost berkeley-db@4 qt@5 miniupnpc libnatpmp zeromq librsvg

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --with-gui=yes

      - name: make
        run: make -j3

      - name: check
        run: make check
        
